{% set name = "fints" %}
{% set version = "4.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fints-{{ version }}.tar.gz
  sha256: e2d9a2e727b178e923a3b2fae0bd6ecd92bd349a3cddb810481b8d07141f76e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - bleach
    - mt940
    - requests
    - sepaxml >=2.1,<3.dev0
    - enum_tools >=0.12.0,<0.13.dev0

test:
  imports:
    - fints
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://python-fints.readthedocs.io
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: FinTS client library for Python
  description: |
    Many operations in FinTS will require a form of two-step
    authentication, called TANs. TANs are mostly required for operations
    that move money or change details of a bank account. TANs can be
    generated with a multitude of methods, including paper lists, 
    smartcard readers, SMS messages, and smartphone apps.
  doc_url: https://python-fints.readthedocs.io
  dev_url: https://github.com/raphaelm/python-fints

extra:
  recipe-maintainers:
    - jan-janssen
