{% set name = "fints" %}
{% set version = "4.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fints-{{ version }}.tar.gz
  sha256: 9d96974cebe1807bbf2d16e2f3e9f96291a824525a83ee1302cfb52838697b0a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - bleach
    - mt940
    - requests
    - sepaxml >=2.1,<3.dev0
    - enum_tools >=0.12.0,<0.13.dev0

test:
  imports:
    - fints
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://python-fints.readthedocs.io
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: FinTS client library for Python
  description: |
    Many operations in FinTS will require a form of two-step
    authentication, called TANs. TANs are mostly required for operations
    that move money or change details of a bank account. TANs can be
    generated with a multitude of methods, including paper lists, 
    smartcard readers, SMS messages, and smartphone apps.
  doc_url: https://python-fints.readthedocs.io
  dev_url: https://github.com/raphaelm/python-fints

extra:
  recipe-maintainers:
    - jan-janssen
