{% set name = "fints" %}
{% set version = "3.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fints-{{ version }}.tar.gz
  sha256: 426f6af1a79dce75ef9d475da926c8fc407c1bb3da13acf9fb52f5f0449b58d8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bleach
    - mt940
    - python >=3.6
    - requests
    - sepaxml ==2.1.0

test:
  imports:
    - fints
    - fints.hhd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://python-fints.readthedocs.io
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: FinTS client library for Python
  description: |
    Many operations in FinTS will require a form of two-step
    authentication, called TANs. TANs are mostly required for operations
    that move money or change details of a bank account. TANs can be
    generated with a multitude of methods, including paper lists, 
    smartcard readers, SMS messages, and smartphone apps.
  doc_url: https://python-fints.readthedocs.io
  dev_url: https://github.com/raphaelm/python-fints

extra:
  recipe-maintainers:
    - jan-janssen
